package parser

import (
	"io"

	"github.com/LiterMC/wasm-jdk/ir"
	"github.com/LiterMC/wasm-jdk/ops"
)

var _ IRParser = (*noOperandParser)(nil)

type noOperandParser struct {
	Singleton ir.IR
}

func (p *noOperandParser) Op() ops.Op {
	return p.Singleton.Op()
}

func (p *noOperandParser) Parse(br io.ByteReader) (ir.IR, error) {
	return p.Singleton, nil
}

var noOpParsers = []noOperandParser{
	noOperandParser{Singleton: (*ir.IRareturn)(nil)},
	noOperandParser{Singleton: (*ir.IRdreturn)(nil)},
	noOperandParser{Singleton: (*ir.IRdup)(nil)},
	noOperandParser{Singleton: (*ir.IRdup_x1)(nil)},
	noOperandParser{Singleton: (*ir.IRdup_x2)(nil)},
	noOperandParser{Singleton: (*ir.IRdup2)(nil)},
	noOperandParser{Singleton: (*ir.IRdup2_x1)(nil)},
	noOperandParser{Singleton: (*ir.IRdup2_x2)(nil)},
	noOperandParser{Singleton: (*ir.IRfreturn)(nil)},
	noOperandParser{Singleton: (*ir.IRireturn)(nil)},
	noOperandParser{Singleton: (*ir.IRlreturn)(nil)},
	noOperandParser{Singleton: (*ir.IRmonitorenter)(nil)},
	noOperandParser{Singleton: (*ir.IRmonitorexit)(nil)},
	noOperandParser{Singleton: (*ir.IRnop)(nil)},
	noOperandParser{Singleton: (*ir.IRpop)(nil)},
	noOperandParser{Singleton: (*ir.IRpop2)(nil)},
	noOperandParser{Singleton: (*ir.IRreturn)(nil)},
	noOperandParser{Singleton: (*ir.IRswap)(nil)},
	noOperandParser{Singleton: (*ir.IRaaload)(nil)},
	noOperandParser{Singleton: (*ir.IRaastore)(nil)},
	noOperandParser{Singleton: (*ir.IRaconst_null)(nil)},
	noOperandParser{Singleton: (*ir.IRaload_0)(nil)},
	noOperandParser{Singleton: (*ir.IRaload_1)(nil)},
	noOperandParser{Singleton: (*ir.IRaload_2)(nil)},
	noOperandParser{Singleton: (*ir.IRaload_3)(nil)},
	noOperandParser{Singleton: (*ir.IRarraylength)(nil)},
	noOperandParser{Singleton: (*ir.IRastore_0)(nil)},
	noOperandParser{Singleton: (*ir.IRastore_1)(nil)},
	noOperandParser{Singleton: (*ir.IRastore_2)(nil)},
	noOperandParser{Singleton: (*ir.IRastore_3)(nil)},
	noOperandParser{Singleton: (*ir.IRathrow)(nil)},
	noOperandParser{Singleton: (*ir.IRbaload)(nil)},
	noOperandParser{Singleton: (*ir.IRbastore)(nil)},
	noOperandParser{Singleton: (*ir.IRcaload)(nil)},
	noOperandParser{Singleton: (*ir.IRcastore)(nil)},
	noOperandParser{Singleton: (*ir.IRsaload)(nil)},
	noOperandParser{Singleton: (*ir.IRsastore)(nil)},
	noOperandParser{Singleton: (*ir.IRd2f)(nil)},
	noOperandParser{Singleton: (*ir.IRd2i)(nil)},
	noOperandParser{Singleton: (*ir.IRd2l)(nil)},
	noOperandParser{Singleton: (*ir.IRdadd)(nil)},
	noOperandParser{Singleton: (*ir.IRdaload)(nil)},
	noOperandParser{Singleton: (*ir.IRdastore)(nil)},
	noOperandParser{Singleton: (*ir.IRdcmpg)(nil)},
	noOperandParser{Singleton: (*ir.IRdcmpl)(nil)},
	noOperandParser{Singleton: (*ir.IRdconst_0)(nil)},
	noOperandParser{Singleton: (*ir.IRdconst_1)(nil)},
	noOperandParser{Singleton: (*ir.IRddiv)(nil)},
	noOperandParser{Singleton: (*ir.IRdload_0)(nil)},
	noOperandParser{Singleton: (*ir.IRdload_1)(nil)},
	noOperandParser{Singleton: (*ir.IRdload_2)(nil)},
	noOperandParser{Singleton: (*ir.IRdload_3)(nil)},
	noOperandParser{Singleton: (*ir.IRdmul)(nil)},
	noOperandParser{Singleton: (*ir.IRdneg)(nil)},
	noOperandParser{Singleton: (*ir.IRdrem)(nil)},
	noOperandParser{Singleton: (*ir.IRdstore_0)(nil)},
	noOperandParser{Singleton: (*ir.IRdstore_1)(nil)},
	noOperandParser{Singleton: (*ir.IRdstore_2)(nil)},
	noOperandParser{Singleton: (*ir.IRdstore_3)(nil)},
	noOperandParser{Singleton: (*ir.IRdsub)(nil)},
	noOperandParser{Singleton: (*ir.IRf2d)(nil)},
	noOperandParser{Singleton: (*ir.IRf2i)(nil)},
	noOperandParser{Singleton: (*ir.IRf2l)(nil)},
	noOperandParser{Singleton: (*ir.IRfadd)(nil)},
	noOperandParser{Singleton: (*ir.IRfaload)(nil)},
	noOperandParser{Singleton: (*ir.IRfastore)(nil)},
	noOperandParser{Singleton: (*ir.IRfcmpg)(nil)},
	noOperandParser{Singleton: (*ir.IRfcmpl)(nil)},
	noOperandParser{Singleton: (*ir.IRfconst_0)(nil)},
	noOperandParser{Singleton: (*ir.IRfconst_1)(nil)},
	noOperandParser{Singleton: (*ir.IRfconst_2)(nil)},
	noOperandParser{Singleton: (*ir.IRfdiv)(nil)},
	noOperandParser{Singleton: (*ir.IRfload_0)(nil)},
	noOperandParser{Singleton: (*ir.IRfload_1)(nil)},
	noOperandParser{Singleton: (*ir.IRfload_2)(nil)},
	noOperandParser{Singleton: (*ir.IRfload_3)(nil)},
	noOperandParser{Singleton: (*ir.IRfmul)(nil)},
	noOperandParser{Singleton: (*ir.IRfneg)(nil)},
	noOperandParser{Singleton: (*ir.IRfrem)(nil)},
	noOperandParser{Singleton: (*ir.IRfstore_0)(nil)},
	noOperandParser{Singleton: (*ir.IRfstore_1)(nil)},
	noOperandParser{Singleton: (*ir.IRfstore_2)(nil)},
	noOperandParser{Singleton: (*ir.IRfstore_3)(nil)},
	noOperandParser{Singleton: (*ir.IRfsub)(nil)},
	noOperandParser{Singleton: (*ir.IRi2b)(nil)},
	noOperandParser{Singleton: (*ir.IRi2c)(nil)},
	noOperandParser{Singleton: (*ir.IRi2d)(nil)},
	noOperandParser{Singleton: (*ir.IRi2f)(nil)},
	noOperandParser{Singleton: (*ir.IRi2l)(nil)},
	noOperandParser{Singleton: (*ir.IRi2s)(nil)},
	noOperandParser{Singleton: (*ir.IRiadd)(nil)},
	noOperandParser{Singleton: (*ir.IRiaload)(nil)},
	noOperandParser{Singleton: (*ir.IRiand)(nil)},
	noOperandParser{Singleton: (*ir.IRiastore)(nil)},
	noOperandParser{Singleton: (*ir.IRiconst_m1)(nil)},
	noOperandParser{Singleton: (*ir.IRiconst_0)(nil)},
	noOperandParser{Singleton: (*ir.IRiconst_1)(nil)},
	noOperandParser{Singleton: (*ir.IRiconst_2)(nil)},
	noOperandParser{Singleton: (*ir.IRiconst_3)(nil)},
	noOperandParser{Singleton: (*ir.IRiconst_4)(nil)},
	noOperandParser{Singleton: (*ir.IRiconst_5)(nil)},
	noOperandParser{Singleton: (*ir.IRidiv)(nil)},
	noOperandParser{Singleton: (*ir.IRiload_0)(nil)},
	noOperandParser{Singleton: (*ir.IRiload_1)(nil)},
	noOperandParser{Singleton: (*ir.IRiload_2)(nil)},
	noOperandParser{Singleton: (*ir.IRiload_3)(nil)},
	noOperandParser{Singleton: (*ir.IRimul)(nil)},
	noOperandParser{Singleton: (*ir.IRineg)(nil)},
	noOperandParser{Singleton: (*ir.IRior)(nil)},
	noOperandParser{Singleton: (*ir.IRirem)(nil)},
	noOperandParser{Singleton: (*ir.IRishl)(nil)},
	noOperandParser{Singleton: (*ir.IRishr)(nil)},
	noOperandParser{Singleton: (*ir.IRistore_0)(nil)},
	noOperandParser{Singleton: (*ir.IRistore_1)(nil)},
	noOperandParser{Singleton: (*ir.IRistore_2)(nil)},
	noOperandParser{Singleton: (*ir.IRistore_3)(nil)},
	noOperandParser{Singleton: (*ir.IRisub)(nil)},
	noOperandParser{Singleton: (*ir.IRiushr)(nil)},
	noOperandParser{Singleton: (*ir.IRixor)(nil)},
	noOperandParser{Singleton: (*ir.IRl2d)(nil)},
	noOperandParser{Singleton: (*ir.IRl2f)(nil)},
	noOperandParser{Singleton: (*ir.IRl2i)(nil)},
	noOperandParser{Singleton: (*ir.IRladd)(nil)},
	noOperandParser{Singleton: (*ir.IRlaload)(nil)},
	noOperandParser{Singleton: (*ir.IRland)(nil)},
	noOperandParser{Singleton: (*ir.IRlastore)(nil)},
	noOperandParser{Singleton: (*ir.IRlcmp)(nil)},
	noOperandParser{Singleton: (*ir.IRlconst_0)(nil)},
	noOperandParser{Singleton: (*ir.IRlconst_1)(nil)},
	noOperandParser{Singleton: (*ir.IRldiv)(nil)},
	noOperandParser{Singleton: (*ir.IRlload_0)(nil)},
	noOperandParser{Singleton: (*ir.IRlload_1)(nil)},
	noOperandParser{Singleton: (*ir.IRlload_2)(nil)},
	noOperandParser{Singleton: (*ir.IRlload_3)(nil)},
	noOperandParser{Singleton: (*ir.IRlmul)(nil)},
	noOperandParser{Singleton: (*ir.IRlneg)(nil)},
	noOperandParser{Singleton: (*ir.IRlor)(nil)},
	noOperandParser{Singleton: (*ir.IRlrem)(nil)},
	noOperandParser{Singleton: (*ir.IRlshl)(nil)},
	noOperandParser{Singleton: (*ir.IRlshr)(nil)},
	noOperandParser{Singleton: (*ir.IRlstore_0)(nil)},
	noOperandParser{Singleton: (*ir.IRlstore_1)(nil)},
	noOperandParser{Singleton: (*ir.IRlstore_2)(nil)},
	noOperandParser{Singleton: (*ir.IRlstore_3)(nil)},
	noOperandParser{Singleton: (*ir.IRlsub)(nil)},
	noOperandParser{Singleton: (*ir.IRlushr)(nil)},
	noOperandParser{Singleton: (*ir.IRlxor)(nil)},
}
