package parser

import (
	"bytes"

	"github.com/LiterMC/wasm-jdk/ir"
	"github.com/LiterMC/wasm-jdk/ops"
)

var _ ICParser = (*noOperandParser)(nil)

type noOperandParser struct {
	Singleton ir.IC
}

func (p *noOperandParser) Op() ops.Op {
	return p.Singleton.Op()
}

func (p *noOperandParser) Parse(br *bytes.Reader) (ir.IC, error) {
	return p.Singleton, nil
}

var noOperandParsers = []noOperandParser{
	noOperandParser{Singleton: (*ir.ICareturn)(nil)},
	noOperandParser{Singleton: (*ir.ICdreturn)(nil)},
	noOperandParser{Singleton: (*ir.ICdup)(nil)},
	noOperandParser{Singleton: (*ir.ICdup_x1)(nil)},
	noOperandParser{Singleton: (*ir.ICdup_x2)(nil)},
	noOperandParser{Singleton: (*ir.ICdup2)(nil)},
	noOperandParser{Singleton: (*ir.ICdup2_x1)(nil)},
	noOperandParser{Singleton: (*ir.ICdup2_x2)(nil)},
	noOperandParser{Singleton: (*ir.ICfreturn)(nil)},
	noOperandParser{Singleton: (*ir.ICireturn)(nil)},
	noOperandParser{Singleton: (*ir.IClreturn)(nil)},
	noOperandParser{Singleton: (*ir.ICmonitorenter)(nil)},
	noOperandParser{Singleton: (*ir.ICmonitorexit)(nil)},
	noOperandParser{Singleton: (*ir.ICnop)(nil)},
	noOperandParser{Singleton: (*ir.ICpop)(nil)},
	noOperandParser{Singleton: (*ir.ICpop2)(nil)},
	noOperandParser{Singleton: (*ir.ICreturn)(nil)},
	noOperandParser{Singleton: (*ir.ICswap)(nil)},
	noOperandParser{Singleton: (*ir.ICaaload)(nil)},
	noOperandParser{Singleton: (*ir.ICaastore)(nil)},
	noOperandParser{Singleton: (*ir.ICaconst_null)(nil)},
	noOperandParser{Singleton: (*ir.ICaload_0)(nil)},
	noOperandParser{Singleton: (*ir.ICaload_1)(nil)},
	noOperandParser{Singleton: (*ir.ICaload_2)(nil)},
	noOperandParser{Singleton: (*ir.ICaload_3)(nil)},
	noOperandParser{Singleton: (*ir.ICarraylength)(nil)},
	noOperandParser{Singleton: (*ir.ICastore_0)(nil)},
	noOperandParser{Singleton: (*ir.ICastore_1)(nil)},
	noOperandParser{Singleton: (*ir.ICastore_2)(nil)},
	noOperandParser{Singleton: (*ir.ICastore_3)(nil)},
	noOperandParser{Singleton: (*ir.ICathrow)(nil)},
	noOperandParser{Singleton: (*ir.ICbaload)(nil)},
	noOperandParser{Singleton: (*ir.ICbastore)(nil)},
	noOperandParser{Singleton: (*ir.ICcaload)(nil)},
	noOperandParser{Singleton: (*ir.ICcastore)(nil)},
	noOperandParser{Singleton: (*ir.ICsaload)(nil)},
	noOperandParser{Singleton: (*ir.ICsastore)(nil)},
	noOperandParser{Singleton: (*ir.ICd2f)(nil)},
	noOperandParser{Singleton: (*ir.ICd2i)(nil)},
	noOperandParser{Singleton: (*ir.ICd2l)(nil)},
	noOperandParser{Singleton: (*ir.ICdadd)(nil)},
	noOperandParser{Singleton: (*ir.ICdaload)(nil)},
	noOperandParser{Singleton: (*ir.ICdastore)(nil)},
	noOperandParser{Singleton: (*ir.ICdcmpg)(nil)},
	noOperandParser{Singleton: (*ir.ICdcmpl)(nil)},
	noOperandParser{Singleton: (*ir.ICdconst_0)(nil)},
	noOperandParser{Singleton: (*ir.ICdconst_1)(nil)},
	noOperandParser{Singleton: (*ir.ICddiv)(nil)},
	noOperandParser{Singleton: (*ir.ICdload_0)(nil)},
	noOperandParser{Singleton: (*ir.ICdload_1)(nil)},
	noOperandParser{Singleton: (*ir.ICdload_2)(nil)},
	noOperandParser{Singleton: (*ir.ICdload_3)(nil)},
	noOperandParser{Singleton: (*ir.ICdmul)(nil)},
	noOperandParser{Singleton: (*ir.ICdneg)(nil)},
	noOperandParser{Singleton: (*ir.ICdrem)(nil)},
	noOperandParser{Singleton: (*ir.ICdstore_0)(nil)},
	noOperandParser{Singleton: (*ir.ICdstore_1)(nil)},
	noOperandParser{Singleton: (*ir.ICdstore_2)(nil)},
	noOperandParser{Singleton: (*ir.ICdstore_3)(nil)},
	noOperandParser{Singleton: (*ir.ICdsub)(nil)},
	noOperandParser{Singleton: (*ir.ICf2d)(nil)},
	noOperandParser{Singleton: (*ir.ICf2i)(nil)},
	noOperandParser{Singleton: (*ir.ICf2l)(nil)},
	noOperandParser{Singleton: (*ir.ICfadd)(nil)},
	noOperandParser{Singleton: (*ir.ICfaload)(nil)},
	noOperandParser{Singleton: (*ir.ICfastore)(nil)},
	noOperandParser{Singleton: (*ir.ICfcmpg)(nil)},
	noOperandParser{Singleton: (*ir.ICfcmpl)(nil)},
	noOperandParser{Singleton: (*ir.ICfconst_0)(nil)},
	noOperandParser{Singleton: (*ir.ICfconst_1)(nil)},
	noOperandParser{Singleton: (*ir.ICfconst_2)(nil)},
	noOperandParser{Singleton: (*ir.ICfdiv)(nil)},
	noOperandParser{Singleton: (*ir.ICfload_0)(nil)},
	noOperandParser{Singleton: (*ir.ICfload_1)(nil)},
	noOperandParser{Singleton: (*ir.ICfload_2)(nil)},
	noOperandParser{Singleton: (*ir.ICfload_3)(nil)},
	noOperandParser{Singleton: (*ir.ICfmul)(nil)},
	noOperandParser{Singleton: (*ir.ICfneg)(nil)},
	noOperandParser{Singleton: (*ir.ICfrem)(nil)},
	noOperandParser{Singleton: (*ir.ICfstore_0)(nil)},
	noOperandParser{Singleton: (*ir.ICfstore_1)(nil)},
	noOperandParser{Singleton: (*ir.ICfstore_2)(nil)},
	noOperandParser{Singleton: (*ir.ICfstore_3)(nil)},
	noOperandParser{Singleton: (*ir.ICfsub)(nil)},
	noOperandParser{Singleton: (*ir.ICi2b)(nil)},
	noOperandParser{Singleton: (*ir.ICi2c)(nil)},
	noOperandParser{Singleton: (*ir.ICi2d)(nil)},
	noOperandParser{Singleton: (*ir.ICi2f)(nil)},
	noOperandParser{Singleton: (*ir.ICi2l)(nil)},
	noOperandParser{Singleton: (*ir.ICi2s)(nil)},
	noOperandParser{Singleton: (*ir.ICiadd)(nil)},
	noOperandParser{Singleton: (*ir.ICiaload)(nil)},
	noOperandParser{Singleton: (*ir.ICiand)(nil)},
	noOperandParser{Singleton: (*ir.ICiastore)(nil)},
	noOperandParser{Singleton: (*ir.ICiconst_m1)(nil)},
	noOperandParser{Singleton: (*ir.ICiconst_0)(nil)},
	noOperandParser{Singleton: (*ir.ICiconst_1)(nil)},
	noOperandParser{Singleton: (*ir.ICiconst_2)(nil)},
	noOperandParser{Singleton: (*ir.ICiconst_3)(nil)},
	noOperandParser{Singleton: (*ir.ICiconst_4)(nil)},
	noOperandParser{Singleton: (*ir.ICiconst_5)(nil)},
	noOperandParser{Singleton: (*ir.ICidiv)(nil)},
	noOperandParser{Singleton: (*ir.ICiload_0)(nil)},
	noOperandParser{Singleton: (*ir.ICiload_1)(nil)},
	noOperandParser{Singleton: (*ir.ICiload_2)(nil)},
	noOperandParser{Singleton: (*ir.ICiload_3)(nil)},
	noOperandParser{Singleton: (*ir.ICimul)(nil)},
	noOperandParser{Singleton: (*ir.ICineg)(nil)},
	noOperandParser{Singleton: (*ir.ICior)(nil)},
	noOperandParser{Singleton: (*ir.ICirem)(nil)},
	noOperandParser{Singleton: (*ir.ICishl)(nil)},
	noOperandParser{Singleton: (*ir.ICishr)(nil)},
	noOperandParser{Singleton: (*ir.ICistore_0)(nil)},
	noOperandParser{Singleton: (*ir.ICistore_1)(nil)},
	noOperandParser{Singleton: (*ir.ICistore_2)(nil)},
	noOperandParser{Singleton: (*ir.ICistore_3)(nil)},
	noOperandParser{Singleton: (*ir.ICisub)(nil)},
	noOperandParser{Singleton: (*ir.ICiushr)(nil)},
	noOperandParser{Singleton: (*ir.ICixor)(nil)},
	noOperandParser{Singleton: (*ir.ICl2d)(nil)},
	noOperandParser{Singleton: (*ir.ICl2f)(nil)},
	noOperandParser{Singleton: (*ir.ICl2i)(nil)},
	noOperandParser{Singleton: (*ir.ICladd)(nil)},
	noOperandParser{Singleton: (*ir.IClaload)(nil)},
	noOperandParser{Singleton: (*ir.ICland)(nil)},
	noOperandParser{Singleton: (*ir.IClastore)(nil)},
	noOperandParser{Singleton: (*ir.IClcmp)(nil)},
	noOperandParser{Singleton: (*ir.IClconst_0)(nil)},
	noOperandParser{Singleton: (*ir.IClconst_1)(nil)},
	noOperandParser{Singleton: (*ir.ICldiv)(nil)},
	noOperandParser{Singleton: (*ir.IClload_0)(nil)},
	noOperandParser{Singleton: (*ir.IClload_1)(nil)},
	noOperandParser{Singleton: (*ir.IClload_2)(nil)},
	noOperandParser{Singleton: (*ir.IClload_3)(nil)},
	noOperandParser{Singleton: (*ir.IClmul)(nil)},
	noOperandParser{Singleton: (*ir.IClneg)(nil)},
	noOperandParser{Singleton: (*ir.IClor)(nil)},
	noOperandParser{Singleton: (*ir.IClrem)(nil)},
	noOperandParser{Singleton: (*ir.IClshl)(nil)},
	noOperandParser{Singleton: (*ir.IClshr)(nil)},
	noOperandParser{Singleton: (*ir.IClstore_0)(nil)},
	noOperandParser{Singleton: (*ir.IClstore_1)(nil)},
	noOperandParser{Singleton: (*ir.IClstore_2)(nil)},
	noOperandParser{Singleton: (*ir.IClstore_3)(nil)},
	noOperandParser{Singleton: (*ir.IClsub)(nil)},
	noOperandParser{Singleton: (*ir.IClushr)(nil)},
	noOperandParser{Singleton: (*ir.IClxor)(nil)},
}

func init() {
	for i, _ := range noOperandParsers {
		RegisterParser(&noOperandParsers[i])
	}
}
